const SPAM_BRANCH = /^(patch-\d+|update|changes?|fix|main|master|dev)$/i;
const AI_PHRASE = /\b(delve|leverage|seamless(?:ly)?|robust(?:ly)?|comprehensive|utilize|facilitate|ensure that|it is worth noting)\b/i;
const PLACEHOLDER_CODE = /\b(lorem ipsum|password\s*=\s*["']password["']|your[_-]?api[_-]?key|changeme|todo:\s*implement)\b/i;
const GENERATED_MARKER = /\b(generated by copilot|generated by ai|auto-generated by|do not edit manually)\b/i;

export function analyzeBehavioralSignals(input = {}, authorContext = null) {
  if (input.kind === "issue") {
    return emptyBehavioralAnalysis("Behavioral slop checks apply to pull requests and patch submissions.");
  }

  const findings = [];
  const labels = new Set();
  const body = String(input.body || "");
  const title = String(input.title || "");
  const files = Array.isArray(input.files) ? input.files : [];
  const commits = Array.isArray(input.commits) ? input.commits : [];
  const changedFiles = Number(input.changedFiles) || files.length;
  const additions = Number(input.additions) || sum(files, "additions");
  const deletions = Number(input.deletions) || sum(files, "deletions");
  const totalLines = additions + deletions;

  const branch = String(input.headRef || input.branch || input.head?.ref || "");
  if (branch && SPAM_BRANCH.test(branch)) {
    findings.push(finding("suspicious-branch-name", "medium", `Branch name "${branch}" looks like a default or spam pattern.`));
  }

  if (!body.trim() || body.trim().length < 40) {
    findings.push(finding("missing-description", "high", "Description is missing or too short for the touched surface."));
    labels.add("behavioral-risk");
  }

  if (AI_PHRASE.test(`${title}\n${body}`)) {
    findings.push(finding("description-ai-patterns", "medium", "Description uses generic AI-typical phrasing; verify the change is substantively explained."));
  }

  if (changedFiles >= 30) {
    findings.push(finding("file-count", "medium", `Pull request touches ${changedFiles} files, which raises review-budget risk.`));
  }

  if (commits.length <= 1 && totalLines >= 500) {
    findings.push(finding("single-commit-large-diff", "low", "Single commit with a very large diff is harder to review safely."));
  }

  if (totalLines > 0 && additions / Math.max(totalLines, 1) >= 0.95 && changedFiles >= 8) {
    findings.push(finding("change-ratio", "low", "Diff is almost entirely additions across many files."));
  }

  const commitTimes = commits
    .map((commit) => Date.parse(commit.date || commit.committedAt || commit.committed_at || ""))
    .filter((value) => Number.isFinite(value));
  if (commitTimes.length >= 2) {
    const spanSeconds = (Math.max(...commitTimes) - Math.min(...commitTimes)) / 1000;
    if (spanSeconds <= 60 && totalLines >= 120) {
      findings.push(finding("machine-speed-commits", "medium", "Commits were produced within 60 seconds on a non-trivial diff."));
      labels.add("rapid-submission");
    }
  }

  if (authorContext?.recentPrs24h >= 10) {
    findings.push(finding("author-pr-volume", "critical", `Author has ${authorContext.recentPrs24h} pull requests in the last 24 hours.`));
    labels.add("high-pr-volume");
  } else if (authorContext?.recentPrs24h >= 5) {
    findings.push(finding("author-pr-volume", "high", `Author has ${authorContext.recentPrs24h} pull requests in the last 24 hours.`));
    labels.add("high-pr-volume");
  }

  const createdAt = Date.parse(input.createdAt || input.submittedAt || "");
  const firstCommitAt = commitTimes.length ? Math.min(...commitTimes) : NaN;
  if (Number.isFinite(createdAt) && Number.isFinite(firstCommitAt) && totalLines >= 200) {
    const minutes = (createdAt - firstCommitAt) / 60_000;
    if (minutes >= 0 && minutes <= 15) {
      findings.push(finding("submission-speed", "high", "Large pull request was submitted within 15 minutes of the first commit."));
      labels.add("rapid-submission");
    }
  }

  const fileNames = files.map((file) => String(file.filename || file.path || "")).filter(Boolean);
  if (body.length >= 120 && fileNames.length >= 2 && !fileNames.some((name) => body.includes(name.split("/").pop()))) {
    findings.push(finding("description-file-mismatch", "medium", "Long description does not reference any changed file names."));
  }

  const patchText = files.map((file) => String(file.patch || "")).join("\n");
  if (PLACEHOLDER_CODE.test(`${body}\n${patchText}`)) {
    findings.push(finding("placeholder-code", "high", "Placeholder or example credential/code patterns were found."));
    labels.add("behavioral-risk");
  }

  if (GENERATED_MARKER.test(`${body}\n${patchText}`)) {
    findings.push(finding("generated-code-markers", "medium", "Generated-code marker text was found without a reviewable source rationale."));
  }

  const emojiCount = (title + body).match(/[\u{1F300}-\u{1FAFF}]/gu)?.length || 0;
  if (emojiCount >= 8) {
    findings.push(finding("emoji-spam", "low", "Title or description contains excessive emoji."));
  }

  const hard = findings.filter((item) => item.severity === "high" || item.severity === "critical").length;
  const soft = findings.length - hard;
  const checkStatus = hard > 0 ? "fail" : soft > 0 ? "warn" : "pass";
  if (findings.length) labels.add("behavioral-risk");

  return {
    enabled: true,
    checkStatus,
    labels: [...labels],
    findings,
    summary: findings.length
      ? `${findings.length} behavioral signal(s): ${findings.slice(0, 4).map((item) => item.id).join(", ")}`
      : "No behavioral slop or rapid-submission signals detected."
  };
}

function emptyBehavioralAnalysis(summary) {
  return {
    enabled: false,
    checkStatus: "pass",
    labels: [],
    findings: [],
    summary
  };
}

function finding(id, severity, reason) {
  return { id, severity, reason };
}

function sum(items, key) {
  return items.reduce((total, item) => total + Number(item[key] || 0), 0);
}